version: '3.1'

services:
   rodsi-erddap:
      image: axiom/erddap
      restart: always
      ports:
         - 8082:8080
      volumes:
         - ./data/erddap/content:/usr/local/tomcat/content/erddap
         - ./data/erddap/data:/data/erddap/data
